registrar: "alice"

alice:
        mnemonic: "candy eager deal flush pull elite job second art divorce task market cattle term write reform month sphere scissors fluid pumpkin feed issue abstract aunt"

damian:
        mnemonic: "learn cable switch safe increase maze garage museum royal nature dance pair uncle neither become practice bench ball giant curious fabric indicate token able release"

APP_ID: 11